[package]
name = "hovertank-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "^0.13.2", features = ["dynamic_linking", "wayland"]}
bevy_asset_loader = "^0.20.2"
leafwing-input-manager = "^0.13.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
